site_name: Example wiki
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: purple
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime

nav:
  - The Wiki: 'index.md'
  - Project: 'project/project.md'
  - MkDocs:
    - 'Writing MkDocs': 'MkDocs/mkdocs-writing.md'
    - 'CI/CD With MkDocs': 'MkDocs/mkdocs-ci.md'
  - CI/CD:
    - 'Contiuous Integration': 'CI/ci.md'
    - 'Continious Delivery': 'CI/cd.md'
  - Git prehooks:
    - 'prehooks': 'git/prehooks.md'
  - GitHub:
    - Issues and Project board: 'github/issues.md'
    - GitHub Actions: 'github/actions.md'
    - Copilot: 'github/copilot.md'
    - Automated notifications (webhooks): 'github/notifications.md'
  - Meetings:  'meetings/meetings.md'



markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.superfences:
        custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
extra:
  version:
    provider: mike